sudo: false
language: rust
cache: cargo
os:
  - linux
rust:
  - nightly
addons:
  apt:
    packages:
      - libssl-dev
git:
  depth: 1
branches:
  only:
    - master
notifications:
  email: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
after_success:
  - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  - cargo tarpaulin --out Xml
  - bash <(curl -s https://codecov.io/bash)
